### ISSUE TITLE
get inf by n_frames = video.get_meta_data()['nframes']

### ISSUE THREAD

**Issue by csbobby** [aimagelab/mvad-names-dataset#1]
When we test visualize.py for movie clips (e.g. movie 21_JUMP_STREET, clip DVS671), it return 'inf' for video.get_meta_data()['nframes']. 

Clip: 21_JUMP_STREET_DVS671.avi
nframes = inf

**Comment by stefanopini** [comment]
I've just tested the script using the clip `21_JUMP_STREET_DVS671.avi` and it works on my workstation (`n_frames = 124`) with Ubuntu 18.04, Python 3.6.6, imageio 2.4.1 and ffmpeg 3.4.6.

Can you please report your system and environment information? In particular:
- Operating System
- Python version
- imageio version
- ffmpeg version

**Comment by csbobby** [comment]
Already solved, it was because the version issue. Thanks
