### ISSUE TITLE
generating tracks

### ISSUE THREAD

**Issue by jamespark3922** [aimagelab/mvad-names-dataset#2]
which code base did you use to get the tracks?

**Comment by stefanopini** [comment]
We implemented our own algorithm that follows what reported in _Section 3.1_ and _Algorithm 1_ of the paper [M-VAD Names: a Dataset for Video Captioning with Naming](https://link.springer.com/article/10.1007/s11042-018-7040-z).

At the moment, we are not planning to release that code, but you should be able to re-implement it following what is described in the paper.

Feel free to comment on this issue if you need further assistance on this.
